package androidcourse.android.jonaswu.yahoo.com.todolists.dao_helper;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import androidcourse.android.jonaswu.yahoo.com.todolists.dao_helper.todolist;

import androidcourse.android.jonaswu.yahoo.com.todolists.dao_helper.todolistDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todolistDaoConfig;

    private final todolistDao todolistDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todolistDaoConfig = daoConfigMap.get(todolistDao.class).clone();
        todolistDaoConfig.initIdentityScope(type);

        todolistDao = new todolistDao(todolistDaoConfig, this);

        registerDao(todolist.class, todolistDao);
    }
    
    public void clear() {
        todolistDaoConfig.getIdentityScope().clear();
    }

    public todolistDao getTodolistDao() {
        return todolistDao;
    }

}
