package androidcourse.android.jonaswu.yahoo.com.todolists.dao_helper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TODOLIST.
 */
public class todolist {

    private Long id;
    private String name;
    private java.util.Date due;
    private java.util.Date create;

    public todolist() {
    }

    public todolist(Long id) {
        this.id = id;
    }

    public todolist(Long id, String name, java.util.Date due, java.util.Date create) {
        this.id = id;
        this.name = name;
        this.due = due;
        this.create = create;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public java.util.Date getDue() {
        return due;
    }

    public void setDue(java.util.Date due) {
        this.due = due;
    }

    public java.util.Date getCreate() {
        return create;
    }

    public void setCreate(java.util.Date create) {
        this.create = create;
    }

}
